# Generated by Django 5.1 on 2024-08-16 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalutionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppoint',
            name='app_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evalutionapp.app', unique=True),
        ),
    ]
